### ISSUE TITLE
README contains outdated, false information, and the comparison is not "apples to apples"

### ISSUE THREAD

**Issue by pyramation** [coinhall/cosmes#64]
the version of cosmos-kit you compared is over a year old, and has since been reduced in size by a large order of magnitude

<img width="678" alt="Screen Shot 2024-05-03 at 7 02 41 PM" src="https://github.com/coinhall/cosmes/assets/545047/701a549b-720f-463c-9eeb-142d456abef2">

**Comment by pyramation** [comment]
21MB for cosmes:

![Uploading Screen Shot 2024-05-03 at 7.04.25 PM.png…]()

**Comment by AaronCQL** [comment]
Hey @pyramation, thanks for pointing out the outdated benchmarks, we've bumped the following packages to the [latest versions](https://github.com/coinhall/cosmes/commit/4750b44fb73450df52c4b74406116f0f14e7559c#diff-c0e3ad6c29574c7beeb51d54e1c88c7b0e100f44178e07bf8b96cbd41e7abad2L12-L15) within the benchmarks:

https://github.com/coinhall/cosmes/blob/4750b44fb73450df52c4b74406116f0f14e7559c/benchmarks/cosmoskit-v2-react/package.json#L12-L15

And updated the benchmarks to include a timestamp accordingly:

![image](https://github.com/coinhall/cosmes/assets/28671644/9db1a9ef-6625-41b3-8d13-1cc1679febcd)

Note that what is being compared is the **final bundle size**, not the published package size. CosmES is 22MB unpacked when _published_, because it publishes all the TS type definitions, source maps, and all the protobufs needed. It's not just a Cosmos Kit alternative, but also a cosm.js alternative. However, the final output app bundle will always be much smaller than 22MB, because CosmES fully supports tree-shaking, unlike cosm.js which Cosmos Kit depends on.

Please feel free to replicate the benchmarks results - the full methodology is [documented within the README](https://github.com/coinhall/cosmes?tab=readme-ov-file#benchmarks) and the code can be [located within the `benchmarks` folder](https://github.com/coinhall/cosmes/tree/main/benchmarks/cosmoskit-v2-react). If there are any optimisations you'd like to make to minimise the bundle size, please do open a PR as well. The code and benchmark is purposely set to be as "dumb" as possible so it isn't 100% accurate, but is likely what a developer will experience when first using either CosmES or Cosmos Kit.

**Comment by pyramation** [comment]
Hi @AaronCQL,

I wanted to point out that these benchmarks might not be directly comparable. We're looking at two different scopes: our full UI Kit, designed for building complete dApps, versus the cosmes example with all UI components integrated directly into the example itself. For a more apples-to-apples comparison, you might want to look at our @cosmos-kit/react-lite package, which offers similar functionality.

Also, I noticed you're using buf.build. Unless I missed something, it seems like it doesn't support amino encoding, which is essential for securing Ledger transactions. Could you confirm whether amino is supported in your setup? I didn’t see it in the documentation. I understand amino is supposed to be deprecated, but it's not emprically or in production case deprecated at all.

Seems that the main reason we're seeing the big difference is, we are also including a UI, which isn't necessary if you build your own react integration or use our react-lite package, and you've also decided not to use amino encoding. That and obvisously cosmojs 1.0 doesn't support tree-shaking which will change soon

Thanks for checking on this!

**Comment by pyramation** [comment]
Here are some adjustments that can be made. We still need cosmjs to support tree-shaking, and it will, but this should bring the number down a bit:

![Screen Shot 2024-05-05 at 4 31 04 AM](https://github.com/coinhall/cosmes/assets/545047/cc32c561-c82b-40f4-a230-83aca228954f)

```diff
-import { useChain } from "@cosmos-kit/react";
+import { useChain } from "@cosmos-kit/react-lite";
```

```diff
 import "./polyfill.ts";
 
 import { wallets } from "@cosmos-kit/keplr";
-import { ChainProvider } from "@cosmos-kit/react";
-import { assets, chains } from "chain-registry";
+import { ChainProvider } from "@cosmos-kit/react-lite";
+import { chain } from "chain-registry/mainnet/osmosis";
 import React from "react";
 import ReactDOM from "react-dom/client";
 
 import { App } from "./App.tsx";
 
-import "@interchain-ui/react/styles";
 import "./index.css";
 
 const WC_PROJECT_ID = "2b7d5a2da89dd74fed821d184acabf95";
```

```diff
-      chains={chains} // supported chains
-      assetLists={assets} // supported asset lists
+      chains={[chain]} // supported chains
+      // for a more fair comparision, commenting this out since 0 assets are 
+      // assetLists={[assets]} // 
```

**Comment by pyramation** [comment]
And to be clear here is the current comparison to make it a bit more visual of why this is an issue:

| Feature                      | CosmJS+Cosmos-Kit Benchmark             | Cosmes Benchmark       |
|------------------------------|--------------------------------|----------------------|
| Complete UI Kit              | ✅                              | ❌                    |
| Amino Encoding               | ✅                              | ❌                    |
| Supports Ledger Transactions | ✅                              | ❌                    |
| Supports Osmosis             | ✅                              | ✅                    |
| Includes Chain-Registry      | ✅                              | ❌                    |
| Includes All Chains          | ✅                              | ❌                    |
| Includes Assets              | ✅                              | ❌                    |
| Includes All Assets and Denoms | ✅                            | ❌                    |
| Lightweight React Integration| Optional (@cosmos-kit/react-lite) | ✅                  |
| Supports Tree-shaking        | ❌   | ✅                    |

**Comment by pyramation** [comment]
I feel the comparison stating "smaller than cosmos-kit" alone doesn't quite capture the full picture. In reality, the statement should include cosmjs, cosmos-kit, lib sodium, and interchain ui. As many of you are aware, the major contribution of weight comes from these additional libraries, not just cosmos-kit. This distinction is crucial and should be clarified as the current framing could be misleading. We’re working on addressing this, but it’s important to ensure our discussions are accurate and transparent.

**Comment by pyramation** [comment]
Finally, I wanted to say thank you for your work. I'm actually kind of glad this whole comparison thing came up. It's been a great push for us to roll out our new release that supports tree shaking. 

Speaking of which, we've dropped lib sodium for noble in our new release, so that's another update on our end.

Maybe it's time to collaborate? With the upcoming additions in our toolkit, like telescope for amino, proto, and the new sign mode textual, it feels like a natural fit. When both amino and direct signing are deprecated, your team won't be able to use buf-build anymore (which is also not compatible with ledger)

Seriously, I think there's a lot we could achieve together. How about a conversation? We’re gearing up to integrate all these elements soon that would likely make these comparisons negligible, and it could be a game-changer. Let’s chat 🙌🏻
